import type { Metadata } from "next";
import { Belleza, Quicksand } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components";

const quicksand = Quicksand<"--font-quicksand">({
  subsets: ["latin"],
});

const belleza = Belleza<"--font-belleza">({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Perle i konac",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable} ${belleza.variable} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
